### ISSUE TITLE
Webinar3

### ISSUE THREAD

**Issue by cornerofksx** [cornerofksx/Webinar3#1]

**Comment by AlexeiKozlovski** [comment]
1. Нужно указать методологию проекта
2. Кроме разработчиков приложения нужно также backend. Т.к., если я правильно понимаю, это не просто оффлан приложение, а предполагаются дальнейшие интеграции. Думаю будет полезно нарисовать логическую диаграмму аналогично как была по интернет-банку.

**Comment by cornerofksx** [comment]
@AlexeiKozlovski, будет Scrum.
